site_name: Pupsourcing
site_description: Clean Event Sourcing library for Go
site_author: pupsourcing
site_url: https://pupsourcing.gopup.dev

repo_name: pupsourcing/core
repo_url: https://github.com/pupsourcing/core

theme:
  name: null
  custom_dir: custom_theme

nav:
  - Home: index.md
  - Docs:
      - Overview: docs-overview.md
      - Getting Started: getting-started.md
      - Core Concepts: core-concepts.md
      - Consumers: consumers.md
      - Supported Databases: adapters.md
      - Code Generation: eventmap-gen.md
      - Outbox: outbox.md
      - Deployment: deployment.md
      - Observability: observability.md
  - Changelog: changelog.md
  - About: about.md

markdown_extensions:
  admonition: { }
  codehilite:
    guess_lang: false
  toc:
    permalink: true
